#
# This file is part of the PHPProm package.
#
# (c) Philip Lehmann-Böhm <philip@philiplb.de>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#

language: php
services:
    - memcached
    - redis-server
    - mysql
    - postgresql
    - mongodb
before_script:
    - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - mysql -e 'CREATE DATABASE phppromtest;'
    - composer install
script: vendor/bin/phpunit
php:
    - 5.5.37
    - 5.6.25
    - 7
after_script:
    - php vendor/bin/coveralls -v
